# MYSQL
SELECT
    P.PRODUCT_CODE,
    SUM(OS.SALES_AMOUNT * P.PRICE) AS SALES
FROM
    OFFLINE_SALE OS INNER JOIN PRODUCT P
    ON
    OS.PRODUCT_ID = P.PRODUCT_ID
GROUP BY
    P.PRODUCT_CODE
ORDER BY
    SALES DESC, PRODUCT_CODE