# MYSQL
SELECT 
    YEAR(DIFFERENTIATION_DATE) AS YEAR,
    (
        SELECT
            MAX(ED_TMP.SIZE_OF_COLONY)
        FROM
            ECOLI_DATA ED_TMP
        WHERE
            YEAR = YEAR(ED_TMP.DIFFERENTIATION_DATE)
    ) - SIZE_OF_COLONY AS YEAR_DEV,
    ID
FROM ECOLI_DATA
ORDER BY YEAR, YEAR_DEV