# MYSQL
SELECT
    INS.ANIMAL_ID,
    INS.ANIMAL_TYPE,
    INS.NAME
FROM
    ANIMAL_INS INS INNER JOIN ANIMAL_OUTS OUTS
    ON
    INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE
    (INS.SEX_UPON_INTAKE LIKE "Intact%")
    AND
    (OUTS.SEX_UPON_OUTCOME = "Spayed Female" OR OUTS.SEX_UPON_OUTCOME = "Neutered Male")
ORDER BY INS.ANIMAL_ID;

# JOIN 미사용
SELECT
    ANIMAL_ID,
    ANIMAL_TYPE,
    NAME
FROM
    ANIMAL_OUTS
WHERE
    (SEX_UPON_OUTCOME LIKE "%Spayed%" OR SEX_UPON_OUTCOME LIKE "%Neutered%" )
    AND
    ANIMAL_ID IN (SELECT ANIMAL_ID FROM ANIMAL_INS WHERE SEX_UPON_INTAKE LIKE "%Intact%")
ORDER BY ANIMAL_ID;